### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by frankie567**
# Description

The goal of this PR is to add the base infrastructure for unit testing the backend and implement tests for the REST endpoints.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] All GitHub workflows have passed
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by frankie567** [comment]
@KentonParton Before going further, I would like to have your opinion on the Pytest setup, in particular, the approach I took to create test data:

 https://github.com/Swiple/swiple/blob/ee69004adc26cfd4771b1d8ec04f1c33ab113e47/backend/tests/data.py#L1-L29

Basically, we'll define our test data directly in Python using our models. They will be inserted in a mock OpenSearch database when tests are started.

**Comment by KentonParton** [comment]
@frankie567 Using the Pydantic models to insert test data with reduce test maintenance but may disguise breaking changes between versions. Maybe we should have some tests which verify our `model.dict()` outputs against some `dict` value?

I think the same will apply to the payloads that we send to endpoints. I think we want tests to break when the payload model has changed between Swiple version X and version Y.

What are your thoughts on this?

**Comment by frankie567** [comment]
Hmm, I see what you mean. Then, the easiest way could be to just have plain JSON files that we load at startup. This way, we'll quickly see if we made breaking changes to the models.

The drawback is that we'll have to maintain the JSON files, but it may be automated at some point.

**Comment by KentonParton** [comment]
I think for our endpoint tests it would be ok to maintain `json.dumps({'key': 'value'})`. Shouldn't be too bad. We could use Pydantic models for our smaller tests.

**Comment by frankie567** [comment]
> I think for our endpoint tests it would be ok to maintain `json.dumps({'key': 'value'})`. Shouldn't be too bad. We could use Pydantic models for our smaller tests.

Well, I definitely was planning to compare endpoint results with JSON values. 

The main question for me here is: what approach do we take to create test data before starting tests?

**Comment by frankie567** [comment]
@KentonParton What do you think of this approach? 😄 

https://github.com/Swiple/swiple/blob/7982aacb55acbaf73917cfa5c70bb2486626cb85/backend/tests/test_api_v1_datasource.py#L118-L140

**Comment by KentonParton** [comment]
@frankie567 It looks great 🙌

**Comment by frankie567** [comment]
@KentonParton I've implemented unit tests for the following routers:

- [X] Datasources
- [X] Datasets
- [X] Expectations
- [X] Validations

Do you also want tests for other parts or is it okay for starting?

**Comment by KentonParton** [comment]
@frankie567 I think this is a good starting point 👍 Great work

Could we add the tests as a GitHub workflow and update docs `Start Developing` to use `poetry install --with postgres,redshift,mysql,trino,athena,snowflake,aws-secrets,gcp,azure-secrets,dev`.

Will take another look in the AM. Test coverage was showing as 0% for me in PyCharm so I need to see what I've got wrong.

**Comment by frankie567** [comment]
Let's do this!

**Comment by KentonParton** [comment]
Adding Codecov would be very helpful. I have added `secrets.CODECOV_TOKEN`.

**Comment by frankie567** [comment]
Here we go ☂️

**Pull request merged**
